### ISSUE TITLE
feat: item type choice more visual when adding/editing

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#38] opened 2023-03-14 10:11 UTC
make the choice of the item type (offer, request, loan, event) more visual when adding/editing an item, using e.g. radio or radio button (with single option) rather than drop down list

**Comment by banneux-florent** [comment] 2023-11-02 01:20
Duplicate of issue #57 who has been resolved and merged.

**Closed by banneux-florent** 2023-11-02 01:20 UTC
Labels: enhancement
